version: 0.0
os: linux
files:
	- source: .openshift/openshift.inc
	- destination: /var/www/html/
hooks:
	BeforeInstall:
		- location: scripts/instal_dependencies
		  timeout: 300
		  runas: root
		- location: scripts/start_server
		  timeout: 300
		  runas: root
		- location: scripts/stop_server
		  timeout: 300
		  runas: root